### ISSUE TITLE
Help !! How to set cross crop to vertical straight crop?

### ISSUE THREAD

**Issue by vthakkar66** [aliHafizji/SplitImageView#2]
needed straight side of view instead of that triangle !!

**Comment by vthakkar66** [comment]
can you please response ??
I am waiting for your response.
Please help ! i need it..

**Comment by awais-abbas-geekybugs** [comment]
@vthakkar66  i need same thing did you find what you were looking for?

**Comment by vthakkar66** [comment]
> @vthakkar66 i need same thing did you find what you were looking for?

Yes i have found this 
https://github.com/developer--/before_after_slider
